# site globals
title: speen's space
description: speen's collection of cool projects

# contact/socials
email: spencer.d.tenney@gmail.com
fediverse: https://types.pl/@speen
github: https://github.com/spencer-maaaaan
tumblr: https://www.tumblr.com/blog/vim-artisan
youtube: https://www.youtube.com/@predatoru

# enable display of blog collection pages
collections:
  blog:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
